version: '3.4'

services:
  apib2c:
    image: apib2c
    build:
      context: ./MoteeQueso.Api
      dockerfile: MoteeQueso.Api/Dockerfile
    ports:
      - "80:80"
    networks:
      - moteequeso_api

  apiordercustomerb2c:
    image: apiorderscustomerb2c
    build:
      context: ./MoteeQueso.OrdersCustomer.Api
      dockerfile: MoteeQueso.OrdersCustomer.Api/Dockerfile
    ports:
      - "8080:80"
    networks:
      - moteequeso_api

  stock-service:
    build:
        context: ./stock-services
        dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    networks:
      - moteequeso_api

networks:
    moteequeso_api:
