version: '3.4'

services:
  apib2c:
    image: customerpublisherb2c
    build:
      context: ./CustomerPublisher
      dockerfile: Api/Dockerfile
    ports:
      - "8081:80"
    networks:
      - moteequeso_api

  apiordercustomerb2c:
    image: customerb2c
    build:
      context: ./Customer
      dockerfile: Api/Dockerfile
    ports:
      - "8082:80"
    networks:
      - moteequeso_api

networks:
    moteequeso_api:
