version: '3.4'

services:
  customerpublisherb2c:
    image: customerpublisherb2c
    build:
      context: ./CustomerPublisher
      dockerfile: Api/Dockerfile
    ports:
      - "8081:80"
    networks:
      - moteequeso_api

  customerb2c:
    image: customerb2c
    build:
      context: ./Customer
      dockerfile: Api/Dockerfile
    ports:
      - "8082:80"
    networks:
      - moteequeso_api
  
  ordersb2c:
    image: ordersb2c
    build:
      context: ./Order
      dockerfile: Api/Dockerfile
    ports:
      - "8083:80"
    networks:
      - moteequeso_api
  
  orderspublisherb2c:
    image: orderspublisherb2c
    build:
      context: ./OrderPublisher
      dockerfile: Api/Dockerfile
    ports:
      - "8084:80"
    networks:
      - moteequeso_api

networks:
    moteequeso_api:
